cc_library(
    name = "desktop_control_library",
    srcs = ["desktop_control_main.cc"],
    hdrs = ["desktop_control.hpp"],
    deps = [
        "//friday/shared:logging",
        "//friday/shared:config_loader",
    ],
    visibility = [
        "//friday:__pkg__",
    ],
)
