cc_library(
    name = "command_launcher_library",
    srcs = ["command_launcher_main.cc"],
    hdrs = ["command_launcher.hpp"],
    deps = [
        "//friday/shared:logging",
        "//friday/shared:config_loader",
    ],
    visibility = [
        "//friday:__pkg__",
    ],
)
