py_binary(name="toppydat",
          srcs=["toppydat.py"],
          deps=[
              "//friday/audio/keyword_detection/goldfish/shared:goldfish_utils",
          ],
          python_version="PY3",
)

