filegroup(
    name = "test_model",
    srcs = [
        "saved_model.pb",
        "variables/variables.index",
        "variables/variables.data-00000-of-00001",
    ],
    visibility = [
        "//visibility:public",
    ],
)
