py_binary(name="magikarp",
          srcs=["magikarp.py"],
          deps=[
              "//friday/audio/keyword_detection/goldfish/shared:goldfish_utils",
              "//friday/audio/keyword_detection/goldfish/models/shared:feature_extraction",
          ],
          python_version="PY3",
)

