py_library(name="feature_extraction",
           srcs=["audio.py"],
           deps=[],
          visibility = [
            "//friday/audio/keyword_detection/goldfish/models/magikarp:__pkg__",
        ],
)

