
cc_library(
    name = "keyword_detection_library",
    srcs = ["model.cc"],
    deps = [
        "//friday/audio/replay_buffer:replay_buffer_library",
        "//friday/audio/keyword_detection/goldfish:goldfish_library",
        "//friday/shared:logging",
    ],
)
